### PR TITLE
feat: add highlights for mini.pick and mini.statusline

### PR DESCRIPTION
**Pull request by oonamo**
Hello, this is a very nice theme, thank you!.
I have added highlights to mini.pick and mini.statusline to be a bit more consistent with the theme.
The only big problem I see in this change is the visibility of the selected item in the dark theme. I also tested it with linking `MiniPickMatchCurrent` with `PmenuSel` which makes it better, but it is inconsistent with the theme, so I am not sure what highlight it should have.
patama-dark-mini
patana-light-mini

### CODE REVIEW

**Comment by cvigilv** [comment]
Awesome! Will change the selection to the one I think would work better and merge the request. 

Thanks a lot!

**Comment by cvigilv** [comment]
What do you think of this changes?

- Made currently selected more clear linking to Visual
- Made marked bold
- Made matched strings match search
- Preview highlights the line where the match is found
- Cleaner title and search box text (just bold)

Screenshot 2024-06-12 at 10 43 03
Screenshot 2024-06-12 at 10 43 55
Screenshot 2024-06-12 at 10 43 59
Screenshot 2024-06-12 at 10 44 35
Screenshot 2024-06-12 at 10 44 37

**Comment by cvigilv** [comment]
Maybe this dont work so well with the dark theme, but I will tackle the darke theme later since I will change some groups around...

Screenshot 2024-06-12 at 10 47 38
Screenshot 2024-06-12 at 10 47 44

**Comment by oonamo** [comment]
The light theme looks really good with those changes. But yeah, the dark theme needs some changes. It might be worth it to add to the palette something like `ui_selection` so you can set them differently individually for light and dark, and the highlight is reusable with other pickers like Telescope or Fzf-lua.

**Comment by cvigilv** [comment]
I will merge this changes to the `develop` branch in case you are interested in using them. This will be accompanied with some minor changes in the colors and some groups

**Comment by cvigilv** [comment]
Closing in favor orf version to be released by the end of week. Included the work discussed here and added as co-author of commit. Thanks! and sorry for the late response and lack of traction on this PR, life got on the way.

**Pull request closed without merging**
